# Generated by Django 3.1.1 on 2021-05-27 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'basket',
                'verbose_name_plural': 'baskets',
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='')),
                ('profile_image', models.TextField(default='')),
                ('phone_number', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consumer',
                'verbose_name_plural': 'consumers',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.TextField()),
                ('image', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('on_order', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'good',
                'verbose_name_plural': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'goodType',
                'verbose_name_plural': 'goodTypes',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('zip_code', models.IntegerField()),
            ],
            options={
                'verbose_name': 'market',
                'verbose_name_plural': 'markets',
            },
        ),
        migrations.CreateModel(
            name='UnitSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'unitSize',
                'verbose_name_plural': 'unitSizes',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('merchant_name', models.TextField()),
                ('account_number', models.TextField()),
                ('expiration_date', models.DateField()),
                ('creation_date', models.DateField()),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paymentmethods', to='virtumarketapi.consumer')),
            ],
            options={
                'verbose_name': 'payment_method',
                'verbose_name_plural': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('bio', models.TextField(default='')),
                ('profile_image', models.TextField(default='')),
                ('booth_image', models.TextField(default='')),
                ('phone_number', models.TextField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='virtumarketapi.market')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'merchant',
                'verbose_name_plural': 'merchants',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('company_name'), nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='GoodBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='virtumarketapi.basket')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current', to='virtumarketapi.good')),
            ],
            options={
                'verbose_name': 'good_basket',
                'verbose_name_plural': 'good_baskets',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='good_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='good', to='virtumarketapi.goodtype'),
        ),
        migrations.AddField(
            model_name='good',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='goods', to='virtumarketapi.merchant'),
        ),
        migrations.AddField(
            model_name='good',
            name='unit_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='good', to='virtumarketapi.unitsize'),
        ),
        migrations.AddField(
            model_name='basket',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='basket', to='virtumarketapi.consumer'),
        ),
        migrations.AddField(
            model_name='basket',
            name='goods',
            field=models.ManyToManyField(through='virtumarketapi.GoodBasket', to='virtumarketapi.Good'),
        ),
        migrations.AddField(
            model_name='basket',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='basket', to='virtumarketapi.paymentmethod'),
        ),
    ]
